docs(contributing): create issue template for stories
z5labs/megamind pull request #56
Opened 2022-09-24 17:13 UTC by Zaba505

2022-09-24 22:23 UTC, nikitawootten commented
For issue templates I'm a big fan of issue forms:  https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

2022-09-24 23:31 UTC, Zaba505 commented
> For issue templates I'm a big fan of issue forms: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

@nikitawootten  Ooo I like that too. I see though it's only in beta for public projects. Should we wait till it stabilizes or do you think it's already stable enough?

2022-09-24 23:59 UTC, nikitawootten commented
> > For issue templates I'm a big fan of issue forms: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
> 
> @nikitawootten  Ooo I like that too. I see though it's only in beta for public projects. Should we wait till it stabilizes or do you think it's already stable enough?

Oh it's pretty stable imo, my team had been using it for like 4 months without any breaking changes. I can PR this PR if you'd like

2022-09-25 00:05 UTC, Zaba505 commented
Nah I can refactor it. Should have it done soon

2022-09-25 01:25 UTC, nikitawootten requested changes
See suggestions below.

2022-09-25 01:25 UTC, nikitawootten commented on .github/ISSUE_TEMPLATE/story.yaml
> +  - type: textarea
```suggestion
  - type: markdown
```
Text areas are only suitable for short responses.

2022-09-25 01:25 UTC, nikitawootten commented on .github/ISSUE_TEMPLATE/story.yaml
> +  - type: textarea
```suggestion
  - type: markdown
```
Markdown must be used for list content.

2022-09-25 01:25 UTC, nikitawootten commented on .github/ISSUE_TEMPLATE/story.yaml
> +  - type: textarea
```suggestion
  - type: markdown
```
GH flavored markdown allows you to reference issues by #. Text areas are not suitable for this input type.

2022-09-25 01:31 UTC, nikitawootten approved these changes

2022-09-25 01:55 UTC, merged

2022-09-25 01:55 UTC, Zaba505 commented
Closed #55